### ISSUE TITLE
Add support for WebSockets

### ISSUE THREAD

**Issue by bikeoid** [hackgvl/trolley-tracker-api-dot-net#3] opened 2015-08-11 10:39 UTC
Make trolley location updates event driven by WebSockets / SignalR or equivalent technology.

**Comment by jeremywight** [comment] 2017-06-27 23:02
This still would be fun. Any takers? :D

**Comment by brbrown25** [comment] 2017-08-15 22:05
I'm actually moving to Greenville at the end of the month and interested in getting involved with/learn more about this project. I'd be interested in working on this!

**Comment by jeremywight** [comment] 2017-08-15 23:31
Awesome! Join us next month for our monthly meeting Brandon,
https://www.meetup.com/Code-for-Greenville/events/240482152/

**Comment by bikeoid** [comment] 2018-01-20 17:47
At least 3 functions will benefit from Web Sockets to increase responsiveness while reducing traffic:
 o Running trolley positions
 o Stop arrival time updates (1 stop, all stops?)
 o Beacon updates (requires authentication)

**Comment by brbrown25** [comment] 2018-02-11 00:03
When is your next meeting?

**Comment by jeremywight** [comment] 2018-02-11 01:23
Tuesday

**Comment by bikeoid** [comment] 2018-02-11 12:51
Tuesday the 20th, that is.   I won't be able to be at that meeting, but will be at the following hack night meeting on the 27th.

**Comment by brbrown25** [comment] 2018-03-01 22:08
very cool, I actually was out of town during the last meeting for work but am definitely interested in contributing!

**Comment by bikeoid** [comment] 2018-03-02 03:27
I started to look at some options to do this:
 *  SignalR is the native ASP.NET method, but notes about the Android SignalR library indicate flakiness.
 *  Signal.io has some advantage because it is more robust and can easily fall back to polling if the client version of web sockets is incompatible with the server version.  There are good libraries for Javascript, IOS and Android clients.   However it has no native ASP.NET server version.   There is an option to run Socket.io via  iisnode on the server and on Azure - https://github.com/Azure/iisnode ; I don't know how reliable this is.
  * Regular web sockets on both ends - This is probably the simplest in the end but there might be incompatible versions of Web Sockets between some old clients and our server.  We'd just need to roll this out slowly to test.

Any other thoughts?

**Comment by stampthecoder** [comment] 2018-03-02 17:22
I think the robust approach with Signal.io maybe best in this situation to
be more reactive to situations where the incompatibilties may occur.
Although, this may increase complexity by adding the said node on the
server (more maintenance).

On Mar 1, 2018 10:27 PM, "bikeoid" <notifications@github.com> wrote:

I started to look at some options to do this:

   - SignalR is the native ASP.NET method, but notes about the Android
   SignalR library indicate flakiness.
   - Signal.io has some advantage because it is more robust and can easily
   fall back to polling if the client version of web sockets is incompatible
   with the server version. There are good libraries for Javascript, IOS and
   Android clients. However it has no native ASP.NET server version. There
   is an option to run Socket.io via iisnode on the server and on Azure -
   https://github.com/Azure/iisnode <https://github.com/Azure/iisnode> ; I
   don't know how reliable this is.
   - Regular web sockets on both ends - This is probably the simplest in
   the end but there might be incompatible versions of Web Sockets between
   some old clients and our server. We'd just need to roll this out slowly to
   test.

Any other thoughts?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/codeforgreenville/trolley-tracker-api-dot-net/issues/3#issuecomment-369809151>,
or mute the thread

**Comment by brbrown25** [comment] 2018-03-07 16:50
In Java I've used the tyrus websocket client and a couple different on ios, and in dot net land I've used WebSocket4Net.  I think regular websockets would be the way to go.  I definitely agree a slow rollout would be best. maybe even adding it as an option that you could opt in to basically toggle between it using polling or websockets and provide a way to get user feedback on any issues.

**Comment by bikeoid** [comment] 2018-03-07 18:10
Thanks - I was about to come to the same conclusion because node.js on the server end seems to be very sketchy to set up - too many separate setup steps which also complicates development testing and possibly problem troubleshooting if something stops working.

I think what we're doing is simple enough that plain web sockets will be OK.   WebSocket4Net seems to be C# only, and might take more work on the IOS and Android implementation.

**Comment by brbrown25** [comment] 2018-03-08 13:02
Yeah I have had some painful experiences with node based microservices, definitely lots of issues can arise when deployment time comes. Would you like me to take a crack at adding a Websocket endpoint to the project with some tests?

Brandon Brown
(240) 506-8335 (m)

**Comment by bikeoid** [comment] 2018-03-08 17:47
Yes, please go ahead and add a Websocket endpoint

**Comment by brbrown25** [comment] 2018-03-10 21:22
Sounds good will start working on that this week.

**Comment by bikeoid** [comment] 2018-03-20 18:10
Update - Greenlink has requested that we use the API to the new system to get beacon information; that will allow them to discontinue the double cellular data subscription.   So we will use the Web socket only for client location updates and not beacon information.

**Comment by ajhodges** [comment] 2018-03-20 18:13
There is a new system? That's interesting. Are they going to give us time to integrate/test out the reliability/accuracy of the new beacon? And if they have their own tracker does that make all of our work/frontends obsolete?

**Comment by bikeoid** [comment] 2018-03-20 18:23
There was no time limit on the request yet - that does raise the question of obsoleting the entire Trolley Tracker application long term, since the new system has the same functionality.

Their beacon has been under test since 2nd half of last year; I don't know how reliable it is since they have just made the app public.

**Comment by jeremywight** [comment] 2018-03-20 19:02
Yeah seems like it would be good to research what they have and make some
considerations about how our product fits into this new system.

**Comment by brbrown25** [comment] 2018-03-21 13:07
I haven't jump far into this yet, is this something still worth adding?

**Comment by bikeoid** [comment] 2018-03-22 01:08
Let's put this on hold until we get a view of the future since the basic functionality is already in the applications.

**Comment by jeremywight** [comment] 2018-03-22 12:20
Yeah I agree. I'm traveling this week, but next week I'll see if we can
setup a time to chat with Greenlink about this.

**Comment by jeremywight** [comment] 2018-04-09 12:59
Update: TL;DR - We are safe to proceed with Websocket work

We met with GreenLink last week and confirmed that they have no desire to
replace the Trollery Tracker app and see it as serving a different
market/user base. We will however begin transitioning and testing the
location tracking from their other system. Thus we should continue with our
plan to replace the client polling with websocket events.

**Closed** 2023-06-30 14:30 UTC
Labels: help wanted
