### ISSUE TITLE
Trolley Time to Stop Issue

### ISSUE THREAD

**Issue by invisionjeremy** [hackgvl/trolley-tracker-api-dot-net#49] opened 2018-12-24 14:49 UTC
@bikeoid Just wanted to give a heads up. On Sat we caught the trolley at Falls Park and it was only about .5mi away and the iOS app estimated time to stop said 25min, I knew that wouldn't be accurate so I timed it. Trolley 00 took 11min to arrive. Just wanted to give a heads up. I'm not sure if we are using this from the Greenlink system, or if this is our calculation, but I would say that at that far off it is more of a deterrent than a help, as if I didn't know it wasn't going to take that long I probably would have walked instead of waiting. 

Thoughts?

**Comment by bikeoid** [comment] 2018-12-26 17:01
It's probably worth a study to compare the 2 and see if either one will be useful for timing.    Once it's moving on the route past any possible break stop, either method should have been closer than that.

**Comment by bikeoid** [comment] 2019-01-12 01:46
I'm a little rusty on where we left the arrival time, but I think it is still experimental in the IOS app.   I finally ran into this last night and the problem is that the stop time isn't updated consistently in the IOS app.   In my case, the time was frozen at the time I first opened the app.    I terminated and restarted the app and the arrival times were very close to reality.

For now, the workaround is to use the Web App for arrival time testing.

**Comment by jeremywight** [comment] 2019-01-12 01:56
So the time isn’t updating from the iOS app?

**Comment by bikeoid** [comment] 2019-01-12 02:20
That's correct.  I ran a test tonight - 

1. Open the app (Not checked since last night)
2. Check a stop.  - Estimated arrival time matches Web app  (It did update just then)
3. Wait 15 minutes, just opening and closing app as though I was monitoring progress, not checking stop;.
4. Trolleys have passed the stop by 10 minutes.
5. Recheck stop,   Stop time hasn't updated and still indicates the original time.
6. Restart app, now up to date.

**Closed** 2023-06-30 14:30 UTC
